<?php 
$tree=$this->helper('Pulsestorm\HelloWorldMVVM\Helper\Data')->getCategoriesDropdown();
$objectManager =  \Magento\Framework\App\ObjectManager::getInstance(); 
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$store = $storeManager->getStore();
?>
<script type="text/javascript">
    <?php //echo '<pre>';print_r($tree['children']) ?>
    //var children = $H(<?php //echo json_encode($tree['children']) ?>);
    var children = [<?php //$i=1; foreach ($tree['children'] as $key => $value) {
        //echo $key;
        //if(count($tree['children'])>$i){ echo ',';}
        //$i++;
   // } ?>];

    function showCat(obj, level) {
        var $ = jQuery.noConflict();
        //remove subcategories if upper class drop down is selected
        //alert(level);
        for (var i = level+1; i < 10; i++) {
            $('#cat_container_'+i).remove();
            //alert(level);
        }
        //end
        var catId = obj.value;
        level += 1;
        if ($('cat_container_' + level)) {
            $('cat_container_' + level).remove();
        }
        get_sub_cate(catId, function(response) {
            options = response.cate;
            parent_url=response.parent_url;
        });
        //var options = get_sub_cate(catId);
        if(options.length>0){
            var html = '<label>Step ' + parseInt(level-1) + '</label><select id="cat_' + catId + '" onchange="showCat(this, ' + level + ')">';
            html += '<option value="">--Select Subcategory</option>';
            for (var i = 0; i < options.length; i++) {
                html += '<option value="' + options[i].entity_id + '">' + options[i].name + '</option>';
            }
            html += '</select>';
            html = '<div class="col-md-3" id="cat_container_' + level + '">' + html + '</div>';

            $('#sub_cat').append(html);
        }
        else{
            window.location.href=parent_url;
            //alert('No Subcategories exists');
        }
        if(level==3){
           $('#sub_cat').append('<div class="col-md-3" id="cat_container_4"><label>Step 3</label><select disabled=""><option>Select Model</option></select></div>');
        }
    }
    function get_sub_cate(catId, callback){
        /*$.post('<?php echo $store->getBaseUrl()?>hello_mvvm/hello/test', {catId: catId}, function(response)
        {
            return response;
        }, "json");*/
        jQuery.ajax({
          url: "<?php echo $store->getBaseUrl()?>hello_mvvm/hello/test",
          cache: false,
          async : false,
          data:{catId: catId},
          type: "POST",
          dataType:'json',
          success: function(response){
            //jQuery('#sub_cat').html(html);
            console.log(response);
            callback(response);
          }
        });
    }
</script>
<div class="row" id="sub_cat" style="padding:15px;">
    <div class="col-md-3"><h3>find your part:</h3></div>
    <div class="col-md-3">
        <label>Step 1</label>
        <select id="first_cat" onchange="showCat(this, 2)">
            <option>Select Brand</option>
            <?php foreach ($tree['first'] as $cat): ?>
                <option value="<?php echo $cat->getId() ?>"><?php echo $cat->getName() ?></option>
            <?php endforeach ?>
        </select>
    </div>
    <div class="col-md-3" id="cat_container_3">
        <label>Step 2</label>
        <select disabled="">
            <option>Select Series</option>
        </select>
    </div>
    <div class="col-md-3" id="cat_container_4">
        <label>Step 3</label>
        <select disabled="">
            <option>Select Model</option>
        </select>
    </div>
</div>